version: '3.8'

services:
  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot-network

  # InfluxDB
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensor_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password123
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - iot-network

     # Grafana
  grafana:
    image: grafana/grafana:latest # You can choose a specific version or 'latest'
    container_name: grafana
    ports:
      - "3000:3000" # Grafana's default port
    environment:
      # Optional: Set admin user and password for initial setup
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana # Persist Grafana data
    networks:
      - iot-network
    depends_on:
      - influxdb #


  
networks:
  iot-network:
    driver: bridge

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data: